// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package main

import (
	_ "embed"
	"fyne.io/fyne/v2"
)

//go:embed assets/AC_repaire.png
var resourceACrepairePngData []byte
var resourceACrepairePng = &fyne.StaticResource{
	StaticName:    "assets/AC_repaire.png",
	StaticContent: resourceACrepairePngData,
}

//go:embed assets/Home-cleaning.png
var resourceHomeCleaningPngData []byte
var resourceHomeCleaningPng = &fyne.StaticResource{
	StaticName:    "assets/Home-cleaning.png",
	StaticContent: resourceHomeCleaningPngData,
}

//go:embed assets/SkillDarLogo.png
var resourceSkillDarLogoPngData []byte
var resourceSkillDarLogoPng = &fyne.StaticResource{
	StaticName:    "assets/SkillDarLogo.png",
	StaticContent: resourceSkillDarLogoPngData,
}

//go:embed assets/activer.png
var resourceActiverPngData []byte
var resourceActiverPng = &fyne.StaticResource{
	StaticName:    "assets/activer.png",
	StaticContent: resourceActiverPngData,
}

//go:embed assets/appliance_repaire.png
var resourceAppliancerepairePngData []byte
var resourceAppliancerepairePng = &fyne.StaticResource{
	StaticName:    "assets/appliance_repaire.png",
	StaticContent: resourceAppliancerepairePngData,
}

//go:embed assets/deactivate.png
var resourceDeactivatePngData []byte
var resourceDeactivatePng = &fyne.StaticResource{
	StaticName:    "assets/deactivate.png",
	StaticContent: resourceDeactivatePngData,
}

//go:embed assets/electricienIco.png
var resourceElectricienIcoPngData []byte
var resourceElectricienIcoPng = &fyne.StaticResource{
	StaticName:    "assets/electricienIco.png",
	StaticContent: resourceElectricienIcoPngData,
}

//go:embed assets/furniture_assembly.png
var resourceFurnitureassemblyPngData []byte
var resourceFurnitureassemblyPng = &fyne.StaticResource{
	StaticName:    "assets/furniture_assembly.png",
	StaticContent: resourceFurnitureassemblyPngData,
}

//go:embed assets/lock_smith.png
var resourceLocksmithPngData []byte
var resourceLocksmithPng = &fyne.StaticResource{
	StaticName:    "assets/lock_smith.png",
	StaticContent: resourceLocksmithPngData,
}

//go:embed assets/paintingIco.png
var resourcePaintingIcoPngData []byte
var resourcePaintingIcoPng = &fyne.StaticResource{
	StaticName:    "assets/paintingIco.png",
	StaticContent: resourcePaintingIcoPngData,
}

//go:embed assets/plumberIco.png
var resourcePlumberIcoPngData []byte
var resourcePlumberIcoPng = &fyne.StaticResource{
	StaticName:    "assets/plumberIco.png",
	StaticContent: resourcePlumberIcoPngData,
}

//go:embed assets/small_repaire_handyman.png
var resourceSmallrepairehandymanPngData []byte
var resourceSmallrepairehandymanPng = &fyne.StaticResource{
	StaticName:    "assets/small_repaire_handyman.png",
	StaticContent: resourceSmallrepairehandymanPngData,
}

//go:embed assets/water_leakage.png
var resourceWaterleakagePngData []byte
var resourceWaterleakagePng = &fyne.StaticResource{
	StaticName:    "assets/water_leakage.png",
	StaticContent: resourceWaterleakagePngData,
}
